export const mockData = [
  {
    id: 1,
    name: 'Wireless Headphones',
    category: 'Electronics',
    brand: 'Brand A',
    price: 99.99,
    rating: 3.4,
    imageUrl: 'https://example.com/images/headphones.jpg',
  },
  {
    id: 2,
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    brand: 'Brand B',
    price: 49.99,
    rating: 4.0,
    imageUrl: 'https://example.com/images/speaker.jpg',
  },
  {
    id: 3,
    name: 'Running Shoes',
    category: 'Footwear',
    brand: 'Brand C',
    price: 59.99,
    rating: 4.2,
    imageUrl: 'https://example.com/images/shoes.jpg',
  },
  {
    id: 4,
    name: 'Smartphone',
    category: 'Electronics',
    brand: 'Brand D',
    price: 499.99,
    rating: 4.8,
    imageUrl: 'https://example.com/images/smartphone.jpg',
  },
  {
    id: 5,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 199.99,
    rating: 4.7,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
  {
    id: 6,
    name: 'Wireless Headphones',
    category: 'Electronics',
    brand: 'Brand A',
    price: 120.99,
    rating: 4.8,
    imageUrl: 'https://example.com/images/headphones.jpg',
  },
  {
    id: 7,
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    brand: 'Brand B',
    price: 91.99,
    rating: 4.0,
    imageUrl: 'https://example.com/images/speaker.jpg',
  },
  {
    id: 8,
    name: 'Running Shoes',
    category: 'Footwear',
    brand: 'Brand C',
    price: 73.99,
    rating: 4.4,
    imageUrl: 'https://example.com/images/shoes.jpg',
  },
  {
    id: 9,
    name: 'Smartphone',
    category: 'Electronics',
    brand: 'Brand D',
    price: 600.99,
    rating: 4.8,
    imageUrl: 'https://example.com/images/smartphone.jpg',
  },
  {
    id: 10,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 222.99,
    rating: 4.9,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
  {
    id: 11,
    name: 'Fitness Tracker',
    category: 'Electronics',
    brand: 'Brand A',
    price: 85.99,
    rating: 3.7,
    imageUrl: 'https://example.com/images/fitnesstracker.jpg',
  },
  {
    id: 12,
    name: 'Winter Boots',
    category: 'Footwear',
    brand: 'Brand B',
    price: 139.99,
    rating: 4.3,
    imageUrl: 'https://example.com/images/winterboots.jpg',
  },
  {
    id: 13,
    name: 'Denim Jeans',
    category: 'Clothing',
    brand: 'Brand C',
    price: 64.49,
    rating: 4.0,
    imageUrl: 'https://example.com/images/jeans.jpg',
  },
  {
    id: 14,
    name: 'Tablet',
    category: 'Electronics',
    brand: 'Brand D',
    price: 259.99,
    rating: 4.5,
    imageUrl: 'https://example.com/images/tablet.jpg',
  },
  {
    id: 15,
    name: 'Sneakers',
    category: 'Footwear',
    brand: 'Brand E',
    price: 92.99,
    rating: 3.9,
    imageUrl: 'https://example.com/images/sneakers.jpg',
  },
  {
    id: 16,
    name: 'Raincoat',
    category: 'Clothing',
    brand: 'Brand A',
    price: 115.0,
    rating: 4.6,
    imageUrl: 'https://example.com/images/raincoat.jpg',
  },
  {
    id: 17,
    name: 'Smartwatch',
    category: 'Electronics',
    brand: 'Brand B',
    price: 189.49,
    rating: 4.2,
    imageUrl: 'https://example.com/images/smartwatch.jpg',
  },
  {
    id: 18,
    name: 'Sandals',
    category: 'Footwear',
    brand: 'Brand C',
    price: 44.99,
    rating: 3.5,
    imageUrl: 'https://example.com/images/sandals.jpg',
  },
  {
    id: 19,
    name: 'T-shirt',
    category: 'Clothing',
    brand: 'Brand D',
    price: 27.99,
    rating: 4.1,
    imageUrl: 'https://example.com/images/tshirt.jpg',
  },
  {
    id: 20,
    name: 'Gaming Console',
    category: 'Electronics',
    brand: 'Brand E',
    price: 389.99,
    rating: 4.8,
    imageUrl: 'https://example.com/images/console.jpg',
  },
];
